const data = [
  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹14500",
    newPrice: 12500,
    company: "Nike",
    color: "green",
    category: "sneakers",
    id : 1
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: 2,
    reviews: "(123 reviews)",
    prevPrice: "₹7000",
    newPrice: 6200,
    company: "Nike",
    color: "blue",
    category: "sneakers",
    id : 2
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹14000",
    newPrice: 12000,
    company: "Nike",
    color: "white",
    category: "sneakers",
    id : 3
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹15000",
    newPrice: 12000,
    company: "Nike",
    color: "red",
    category: "sneakers",
    id : 4
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: 5,
    reviews: "(123 reviews)",
    prevPrice: "₹10000",
    newPrice: 8000,
    company: "Nike",
    color: "green",
    category: "sneakers",
    id : 5
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹1800",
    newPrice: 1700,
    company: "Nike",
    color: "black",
    category: "sneakers",
    id : 6
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹6000",
    newPrice: 4500,
    company: "Vans",
    color: "green",
    category: "flats",
    id : 7
  },
  {
    title: "DSC Belter Cricket Shoes for Mens",
    url: "https://www.amazon.in/dp/B09M8NXFKK",
    company: "DSC",
    star: 4,
    prevPrice: "₹1500",
    color: "white",
    newPrice: 1200,
    stars: "3.9",
    category: "cricket",
    reviews: "(23 reviews)",
    id : 8,
    img: "https://m.media-amazon.com/images/I/41XYw2UIblL._SY395_SX395_.jpg",
  },
  {
    title: "Bersache Sports Shoes for Men",
    url: "https://www.amazon.in/dp/B09ZDP71MB",
    company: "Bersache",
    star: 4,
    prevPrice: "₹2000",
    category: "sports",
    newPrice: 1700,
    stars: "3.3",
    color: "black",
    id : 9,
    reviews: "(12 reviews)",
    img: "https://m.media-amazon.com/images/I/41vPYUJQeuL._SY395_SX395_.jpg",
  },
  {
    title: "Sparx Men's Synthetic Running Shoes",
    url: "https://www.amazon.in/dp/B00IZ963K4",
    company: "SPARX",
    prevPrice: "₹1800",
    star: 4,
    newPrice: 1600,
    color: "black",
    stars: "4",
    category: "running",
    id: 10,
    reviews: "(224 reviews)",
    img: "https://m.media-amazon.com/images/I/51rlCD1qUkL._SY395_SX395_.jpg",
  },
  {
    title: "Sparx Mens Casual Shoe",
    url: "https://www.amazon.in/dp/B07Y5C47JT",
    company: "SPARX",
    prevPrice: "₹1600",
    id: 11,
    newPrice: 1100,
    color: "white",
    category: "casual",
    stars: "4.2",
    star: 4,
    reviews: "(13913 reviews)",
    img: "https://m.media-amazon.com/images/I/31x8oyJlKOL._SX395_SY395_.jpg",
  },
  {
    url: "https://www.amazon.com/dp/B0B5YMGXJX",
    title: "Adidas Originals Falcon Women's Running Shoes",
    company: "Adidas",
    color: "Black",
    category: "Running shoes",
    reviews: "(123 reviews)",
    star: 5,
    prevPrice: "₹7500",
    newPrice: 6500,
    id: 12,
    img: "https://m.media-amazon.com/images/I/71RhZAdw75L._AC_SX675_.jpg",
  },
  {
    url: "https://www.flipkart.com/adidas-originals-superstar-casuals-men/p/itmbf7fbe0a7aefe",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/q/r/x/-original-imagsqf8etaeyfas.jpeg?q=70&crop=false",
    title: "Adidas Superstar Men's Sneakers",
    company: "Adidas",
    color: "White",
    category: "Sneakers",
    reviews: "(4567 reviews)",
    star: 4,
    id: 13,
    prevPrice: "₹8000",
    newPrice: 7000,
  },
  {
    url: "https://www.amazon.com/adidas-Originals-NMD_R1-Primeblue-Sneaker/dp/B08JH7L8GC",
    img: "https://m.media-amazon.com/images/I/71910-Qw5nL._AC_SX675_.jpg",
    title: "Adidas NMD_R1 Men's Casual Shoes",
    company: "Adidas",
    color: "Black",
    category: "Casual shoes",
    reviews: "(2345 reviews)",
    star: 4,
    id: 14,
    prevPrice: "₹9000",
    newPrice: 8000,
  },
  {
    url: "https://www.flipkart.com/adidas-stan-smith-golf-casuals-men/p/itm2493ce4010a50",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/l/e/9/-original-imahfqz63rhqftyf.jpeg?q=70&crop=false",
    title: "Adidas Stan Smith Women's Sneakers",
    company: "Adidas",
    color: "White",
    id: 15,
    category: "Sneakers",
    reviews: "(789 reviews)",
    starRating: 4,
    prevPrice: "₹7000",
    newPrice: 5500,
  },
  {
    img: "https://m.media-amazon.com/images/I/41KKLTNdQCL._SY695_.jpg",
    title: "Adidas Adilette Shower Slides (Unisex)",
    company: "Adidas",
    color: "Blue",
    category: "Sandals",
    reviews: "(1234 reviews)",
    starRating: 4,
    prevPrice: "₹1500",
    newPrice: 1200,
    id: 16,
  },
  {
    url: "https://www.flipkart.com/mens-footwear/puma~brand/pr?sid=osp,cil",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/l/0/7-397832-7-puma-quarry-limepunch-black-original-imagszfzccvyhbmz.jpeg?q=70&crop=false",
    title: "Puma Cell Splatter Men's Running Shoes",
    company: "Puma",
    color: "Green",
    id: 17,
    category: "Running shoes",
    reviews: "(876 reviews)",
    starRating: 4,
    prevPrice: "₹6000",
    newPrice: 5000,
  },
  {
    url: "https://www.amazon.com/puma-cali/s?k=puma+cali",
    img: "https://m.media-amazon.com/images/I/61yydh-bKFL._AC_SX695_.jpg",
    title: "Puma Cali Women's Casual Sneakers",
    company: "Puma",
    color: "White",
    category: "Casual sneakers",
    reviews: "(3456 reviews)",
    starRating: 4,
    prevPrice: "₹5500",
    newPrice: 4500,
    id: 18,
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹1400",
    newPrice: 1200,
    company: "Vans",
    color: "white",
    category: "flats",
    id: 19,
  },
  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹4900",
    newPrice: 4500,
    company: "Puma",
    color: "green",
    category: "sneakers",
    id: 20,
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹5000",
    newPrice: 4500,
    company: "Puma",
    color: "red",
    category: "sneakers",
    id: 21,
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹4000",
    newPrice: 3500,
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 22,
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹3000",
    newPrice: 2500,
    company: "Puma",
    color: "white",
    category: "sneakers",
    id: 23,
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹4000",
    newPrice: 3500,
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 24,
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹14000",
    newPrice: 12000,
    company: "Puma",
    id: 25,
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹14000",
    newPrice: 12000,
    company: "Vans",
    color: "red",
    category: "flats",
    id: 26,
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹11000",
    newPrice: 9000,
    company: "Vans",
    color: "white",
    category: "sandals",
    id: 27,
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹4000",
    newPrice: 3500,
    company: "Vans",
    color: "blue",
    id: 28,
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹12000",
    newPrice: 10000,
    company: "Nike",
    id: 29,
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹14400",
    id: 30,
    newPrice: 12000,
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹5400",
    newPrice: 4500,
    company: "puma",
    color: "black",
    category: "heels",
    id: 31,
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹5200",
    newPrice: 4500,
    company: "Nike",
    color: "red",
    category: "heels",
    id: 32,
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "₹1400",
    newPrice: 1200,
    company: "Nike",
    color: "black",
    category: "heels",
    id: 33,
  },
  {
    title: "SPARX Mens Walking Shoe",
    url: "https://www.amazon.in/dp/B08WJ1WW77",
    star: 4,
    company: "SPARX",
    prevPrice: "₹1700",
    newPrice: 1400,
    category: "walking",
    color: "black",
    stars: 4.1,
    reviews: "(8454 reviews)",
    id: 34,
    img: "https://m.media-amazon.com/images/I/31s71z7qRHL._SX395_SY395_.jpg",
  },
  {
    title: "Sparx Mens Sport_Shoe",
    url: "https://www.amazon.in/dp/B08PWVWKPB",
    star: 4,
    company: "SPARX",
    prevPrice: "₹1900",
    newPrice: 1600,
    stars: 4.1,
    color: "black",
    category: "sport",
    id: 35,
    reviews: "(9184 reviews)",
    img: "https://m.media-amazon.com/images/I/31ibW3kLwJL._SX395_SY395_.jpg",
  },
  {
    title: "Campus Women's Alexa Running Shoes",
    url: "https://www.amazon.in/dp/B07STYLQRV",
    star: 4,
    company: "Campus",
    category: "running",
    prevPrice: "₹1200",
    newPrice: 1000,
    id: 36,
    color: "black",
    stars: 4.2,
    reviews: "(10443 reviews)",
    img: "https://m.media-amazon.com/images/I/41cSGmH2fpL._SY395_SX395_.jpg",
  },
  {
    title: "Campus Men's Artemis Running Shoes",
    url: "https://www.amazon.in/dp/B09LR4KJG2",
    company: "Campus",
    star: 4,
    prevPrice: "₹1300",
    color: "blue",
    newPrice: 1000,
    category: "running",
    id: 37,
    stars: 3.9,
    reviews: "(2142 reviews)",
    img: "https://m.media-amazon.com/images/I/41As6FXfvjL._SY395_SX395_.jpg",
  },
  {
    title: "Liberty Mens Roger-e Sneaker",
    url: "https://www.amazon.in/dp/B0B9ZFPMD9",
    star: 4,
    company: "Liberty",
    prevPrice: "₹1400",
    newPrice: 1200,
    color: "black",
    stars: 3.7,
    id: 38,
    category: "sneakers",
    reviews: "(264 reviews)",
    img: "https://m.media-amazon.com/images/I/31d92YyVi6L._SY395_SX395_.jpg",
  },
  {
    title: "Bourge Mens Running Shoes",
    url: "https://www.amazon.in/dp/B0C6T16DQ5",
    company: "Bourge",
    prevPrice: "₹1500",
    color: "black",
    star: 4,
    newPrice: 1300,
    id: 39,
    stars: 4,
    category: "running",
    reviews: "(45 reviews)",
    img: "https://m.media-amazon.com/images/I/41u3HZkH4kL._SY395_SX395_.jpg",
  },
  {
    title: "ATHCO Mens Comfort Shoes",
    url: "https://www.amazon.in/dp/B0CMJGMFPL",
    company: "ATHCO",
    prevPrice: "₹1800",
    newPrice: 1500,
    star:4,
    id: 40,
    category: "comfort",
    color: "blue",
    reviews: "(163 reviews)",
    img: "https://m.media-amazon.com/images/I/41nDSe4PLsL._SY395_SX395_.jpg",
  },
  {
    title: "ASIAN Men's White Casual Sneaker Shoes",
    url: "https://www.amazon.in/dp/B0CVTVT79X",
    company: "ASIAN",
    prevPrice: "₹1700",
    newPrice: 1400,
    star: 3,
    category: "sneakers",
    id: 41,
    color: "white",
    reviews: "(16 reviews)",
    img: "https://m.media-amazon.com/images/I/41mUOxRogUL._SY395_SX395_.jpg",
  },
  {
    title: "US Polo Association",
    url: "https://www.amazon.in/dp/B08VWHXJM1",
    company: "U.S. POLO ASSN.",
    prevPrice: "₹2000",
    star: 4,
    newPrice: 1700,
    color: "white",
    id: 42,
    stars: "3.5",
    category: "sneakers",
    reviews: "(495 reviews)",
    img: "https://m.media-amazon.com/images/I/31uHlnPUGML._SY395_SX395_.jpg",
  },
  {
    title: "SPARX Mens Running Shoes",
    url: "https://www.amazon.in/dp/B08K9Q9HYW",
    company: "SPARX",
    prevPrice: "₹1900",
    star: 4,
    color: "black",
    category: "running",
    id: 43,
    newPrice: 1600,
    stars: "4.1",
    reviews: "(6669 reviews)",
    img: "https://m.media-amazon.com/images/I/41VSl+892YL._SX395_SY395_.jpg",
  },
  {
    title: "adidas Mens Running Shoe",
    url: "https://www.amazon.in/dp/B0C4DP2N4Q",
    company: "adidas",
    star: 4,
    prevPrice: "₹2300",
    id: 44,
    newPrice: 2000,
    color: "black",
    stars: "4.7",
    category: "running",
    reviews: "(8 reviews)",
    img: "https://m.media-amazon.com/images/I/31Pr8lg0n0L._SY395_SX395_.jpg",
  },
  {
    title: "Campus Men's Hurricane Running Shoes",
    url: "https://www.amazon.in/dp/B09HCHNNH1",
    company: "Campus",
    prevPrice: "₹1400",
    newPrice: 1200,
    star: 4,
    stars: "4.1",
    color: "blue",
    id: 45,
    category: "running",
    reviews: "(3425 reviews)",
    img: "https://m.media-amazon.com/images/I/413-SFjyr9L._SY395_SX395_.jpg",
  },
  {
    title: "ASICS Men's Running Shoes",
    url: "https://www.amazon.in/dp/B08BXDQ17C",
    company: "ASICS",
    prevPrice: "₹2100",
    star: 4,
    newPrice: 1800,
    stars: "4",
    id: 46,
    color: "black",
    category: "running",
    reviews: "(4441 reviews)",
    img: "https://m.media-amazon.com/images/I/41KWCFuqJEL._SX395_SY395_.jpg",
  },
  {
    title: "Nike Mens Revolution 7",
    url: "https://www.amazon.in/dp/B0CL8K38BQ",
    company: "Nike",
    prevPrice: "₹2500",
    star: 4,
    newPrice: 2200,
    stars: "3.5",
    color: "white",
    category: "running",
    id: 47,
    reviews: "(67 reviews)",
    img: "https://m.media-amazon.com/images/I/317hywOOMGL._SY395_SX395_.jpg",
  },
  {
    title: "Nike Mens Revolution 7 Running Shoe",
    url: "https://www.amazon.in/dp/B0C8TDP3F5",
    company: "Nike",
    prevPrice: "₹2600",
    color: "black",
    category: "running",
    star: 4,
    id : 48,
    newPrice: 2200,
    stars: "4.1",
    reviews: "(11 reviews)",
    img: "https://m.media-amazon.com/images/I/4149M3Nn3VL._SY395_SX395_.jpg",
  },
  {
    title: "adidas Mens Drogo M Running Shoe",
    url: "https://www.amazon.in/dp/B07M8RXP42",
    company: "Adidas",
    prevPrice: "₹1800",
    star: 4,
    newPrice: 1500,
    id: 49,
    stars: "4",
    reviews: "(13239 reviews)",
    color: "white",
    category: "running",
    img: "https://m.media-amazon.com/images/I/31t9fIe2l8L._SX395_SY395_.jpg",
  },
  {
    title: "Campus Mens City-rideRunning Shoe",
    url: "https://www.amazon.in/dp/B07KX3RFXX",
    company: "Campus",
    prevPrice: "₹1500",
    newPrice: 1200,
    stars: "3.7",
    color: "black",
    id: 50,
    category: "running",
    star: 4,
    reviews: "(3229 reviews)",
    img: "https://m.media-amazon.com/images/I/41GzR4ywL5L._SX395_SY395_.jpg",
  },
  {
    title: "ASIAN Women's Paradise-01",
    url: "https://www.amazon.in/dp/B0CL515ZZV",
    company: "ASIAN",
    prevPrice: "₹1400",
    newPrice: 1100,
    color: "white",
    id: 51,
    category: "sneakers",
    star: 4,
    stars: "3.7",
    reviews: "(339 reviews)",
    img: "https://m.media-amazon.com/images/I/41cEW8WuMuL._SY395_SX395_.jpg",
  },
  {
    title: "SPARX Mens Sm-680 Industrial Shoe",
    url: "https://www.amazon.in/dp/B098B7QQ8Y",
    company: "SPARX",
    prevPrice: "₹1800",
    newPrice: 1500,
    stars: "4",
    id: 52,
    star: 4,
    reviews: "(2296 reviews)",
    color: "grey",
    category: "industrial",
    img: "https://m.media-amazon.com/images/I/4120Zi2ml6L._SX395_SY395_.jpg",
  },
];

export default data;
